### PR TITLE
0-time records clean up

### PR DESCRIPTION
**Pull request by calexil**
Thanks to @ACIIL for the cleanup

### CODE REVIEW

**Comment by ACIIL** [comment]
Note you will need to start Saltybot as a new install before using the cleaned files, as i understand there is no way to delete previously imported data by gui.

**Comment by calexil** [comment]
don't you just import the data set?

**Comment by reconman** [comment]
Yup, imported data will delete the previous data.

**Comment by calexil** [comment]
@reconman thought so

**Comment by ACIIL** [comment]
I thought it merges the two, removing duplicates?   I think i just lost a bit of data now....

**Pull request merged**
