### PR TITLE
readme cleanup, codefactor.io scan

### PR DESCRIPTION
**Pull request by calexil**
readme cleanup, codefactor.io scan

### CODE REVIEW

**Comment by calexil** [comment]
@reconman I just beautified them for easier reading, if they need edits in the future

**Comment by reconman** [comment]
Yeah but you've added some files.

**Comment by calexil** [comment]
oops those are backups, Ill cut em out

**Comment by reconman** [comment]
While you're at it you can combine your commits into one with git rebase.

**Comment by calexil** [comment]
is there a simple way to do that...

the rebase -i guide is like greek to me

**Comment by reconman** [comment]
This is a good video tutorial for squashing commits: https://youtu.be/9sQIY8c6J64?t=5m55s

I've only watched the first 2 minutes starting at that point but it looks well made.

**Comment by reconman** [comment]
At the end if you try to push the rebased changes, it will tell you that your branch is out of date and you need to pull. **Don't do it!**

Instead do
`git push -f`

**Comment by calexil** [comment]
almost got it all squashed

**Comment by calexil** [comment]
I cant seem to get the two commits squashed, so hopefully you can deal with that

**Comment by reconman** [comment]
Yeah that's fine.

Please note that you should avoid rebasing commits someone else pulled already because all rebased commits are treated like completely new commits. You had to use git push -f to delete the old commits from your own repository history.

For example if I merged your pull request and you rebased it after that, I would have to delete your old commits from my repository history and pull your rebased commits.

**Pull request merged**
