### PR TITLE
Master

### PR DESCRIPTION
**Pull request by ACIIL**
My latest breeding, sort heirustics, and mutation changes.  Value comments and "ok" defaults.  Tested against the new  80k+ dataset with purged bad times.

Also contains merged in updates from the last few days.

### CODE REVIEW

**Comment by ACIIL** [comment]
Had to resolve some bits here on site, everything resolved was related to my code.      I'm sure its ok now, yet still i feel uneasy after resolving.

**Comment by calexil** [comment]
@ACIIL re pull my master so you have the updated structure and add your changes in the src folder

**Comment by ACIIL** [comment]
How would i even see @calexil 's branch in github desktop as this is a fork of  synkarius's main? 

This is for synkarius/new-mutation-method,  and it updates from synkarius/master only.

**Comment by ACIIL** [comment]
Also its not ready for mainline use until a few variables are ported onto the config settings and GUI.  Many ways to tinker how the sim works with no known best way.   See https://github.com/ACIIL/saltbot/projects.     

I guess this was given its own branch on synkarius asnew-mutation-method so the more aware SB users can help test it.

**Comment by calexil** [comment]
ah no worries, but If you wanna get your file structure cleaner, thats what I have done. as well as some sleek readme edits ^ ^

**Comment by reconman** [comment]
Merging this will take a long time because I have to look through all the commits listed here.

**Comment by ACIIL** [comment]
You referring to rebaseing and the such?    I noticed if if pull rquest into my own branches github has a dropdown on site to rebase and something else,  yet i do not see it here. Do you see it with write permissions?

**Comment by reconman** [comment]
Yeah I could do it automatically with one button click but the commit history would be horrid and I wouldn't know what changed.

There are 100 commits in your pull request and many of the commits are already merged into new-mutation-method.

I want to look through all the changes you've made and not just blindly accept them.

**Comment by ACIIL** [comment]
Why are there new conflicts now? I fixed them! I cannot even see what happened.


I think it is in the nature of working and maintaining a fork, that you will see bombs of commits as make release ready branches every few days, trying to pull it over.

Commits is love, is life.
_(｡ﾟ⊿ 」∠)_




Next time i'll just let you guys say when its looks ok to pull over.

**Comment by bergerst** [comment]
I merged the changes from master to the branch, that's what happened.

**Comment by reconman** [comment]
I merged the last changes into the fork from master, that's what happened.

**Comment by ACIIL** [comment]
I should be closing this soon.  Its kinda outdated now.

**Comment by ACIIL** [comment]
The new develop is definitely better now. Closing as to prevent confusion with older bugs.

**Pull request closed without merging**
