### PR TITLE
records and chromosome data consolidated, old stuff cleaned

### PR DESCRIPTION
**Pull request by calexil**

### CODE REVIEW

**Comment by calexil** [comment]
had to get caught up with main branch, I was missing saltbot keep alive in settings somehow

**Comment by calexil** [comment]
had to catch up to you @reconman , this has a cleaner structure, the data, and chromosome

**Comment by calexil** [comment]
this would be easier if I had write access, but w/e

**Comment by calexil** [comment]
@reconman this should be ready now, I removed my old data on trying to make a keep alive script since you figured it out.

I have done some file consolidation as well.

**Comment by calexil** [comment]
@reconman lots of edits to readme, much nicer looking now

**Comment by reconman** [comment]
Merged your changes in commits https://github.com/synkarius/saltbot/commit/b5d6446de718d700e1aa7f7bf6a0a1d4e7627b94 https://github.com/synkarius/saltbot/commit/6e51481479f2dd7b51a0c6ae6e3b167dbb30ee9c and https://github.com/synkarius/saltbot/commit/f1c9b74ee376a28d4742a78743dd587592c41c8b

Before you do anything in your master branch please do this first with the git command line tool:
```
git remote add upstream https://github.com/synkarius/saltbot.git
git fetch upstream
git reset --hard upstream/master
git push
```

Without doing that you will create tons of work for me on your next pull request.

**Comment by calexil** [comment]
I just reforked and did this, hopefully it will make things easier. Also I'm going to try and avoid multiple commits and just do things all at once, sorry for the trouble,

**Comment by reconman** [comment]
Next time just do it as I did and squash commits together. Having 10 readme change commits doesn't look good in the commit history.

**Pull request closed without merging**
