### PR TITLE
Evo sim updates

### PR DESCRIPTION
**Pull request by ACIIL**
Reattempt after my own code merge errors from before.

### CODE REVIEW

**Comment by reconman** [comment]
For a better looking commit history I've squashed together all your commits into one. You can do the same in the future by executing

`git rebase -i <commit hash>`

You need a bit of knowledge about the linux console editor vim for that, though.

I haven't had time to look through your code changes yet since I'm pretty busy at the moment.

**Comment by reconman** [comment]
Why did you revert back my changes where I made it so the sum of chromosome values would be 100?

**Comment by ACIIL** [comment]
Give details to you guys. I really been treating this project as fun and practice.
My git command line practice is bad and i forgotten much over the months. I wanted to focus on readable history over relearning everything git. Commits have be with github app so far.  I can understand my git commits cleaned up as it goes on the main master. I will be keeping them on my fork.

I am planning another change to the normalization code. Originally yes it was my ugly hardcode, and Reconman showed me how to treat it as an array by how JavaScript does its strange things, thank you.  But then i wanted a normalized vector and the rescaling was a  extra step that could create undefined behavior. Normalized vectors look like this, or so how i been treating the chromosome as a set of floats. I don't x100 them on my fork and when i test i don't what a not-normalized vector to be the cause. 

Question for you Reconman, are you sure x100 the values will produces the exact same score heuristics and bet prediction? I would understand x100 the values when making it human readable, but not when it affects the internal data.  So far my glaces at the scores code look makes the math look linear, but it would take a single power or some other math function to break new and old chromosomes imports. I am sure old imports with the normalized scale are affecting scoring and changing the new pools interact in the sim. 

This will need to be considered as you guys choosing to do this merge:
I can say with my fork, old and new chromosomes saves used as import is undefined. People would need start a new pool too trust the results. If i wanted to be sure of this, i would need to do tests with example saves from others see how things changed.  That will take a setup i am not sure how to do.

From my code practice standpoint, i am practiced in c, java, C#; and very little in javascript.  Knowing what and how javascript compares is ongoing and and side goal of all this.  Are there any little code detail in the project i need to know that is not achieved or commented in the original code?

My next goals are improve mutation change scaling, see if i can improve the heuristic, and possibly expand the chromosome with new weights as i want to split the average winning and losing times into separate scores (they appear to scale to one weight atm). 

If you don't take merge, that is cool.

**Comment by ACIIL** [comment]
Studying on Git rebasing.  I have sub branches with commits tweaking values and archived them on my git.   My published here is exactly in the state i want to share. I must not prevent myself from using older branches and commits so i hope nothing breaks the next time i find a reason to go backwards. Git is confusing.

**Pull request merged**
