### PR TITLE
codefactor scan2.0

### PR DESCRIPTION
**Pull request by calexil**
codefactor scan2.0

### CODE REVIEW

**Comment by calexil** [comment]
@reconman @ACIIL @synkarius 

codefactor.io can be dumb at times, but every now and then it catches critical mistakes.

make sure to check out the issue page for any real problems

@synkarius dave, can I get admin for a little bit, I need to setup some webhooks(for a github bot, and codefactor, as well as an experimental extension tester)

you can revoke it if you like

**Comment by reconman** [comment]
The role administrator only exists in repositories for businesses. Private repositories only have one user with owner rights who can create webhooks and whatnot and collaborators with push and merge rights.

**Comment by reconman** [comment]
https://help.github.com/articles/differences-between-user-and-organization-accounts/

**Comment by ACIIL** [comment]
*headscratches
This is too confusing for me.  I am stepping away.....

Be careful with user rights.

**Comment by reconman** [comment]
It was only directed to @calexil anyway.

**Comment by calexil** [comment]
ah well @synkarius  just needs to create the webhook by going to codefactor.io and linking up saltbot

**Pull request merged**
