### PR TITLE
Alternative mutations, betting behaviour, console printouts.

### PR DESCRIPTION
**Pull request by ACIIL**
My develop branch as is and run for a few weeks making salt.
-It is a behind the master fork.
-I think the only real value useful for end users is tweaking 'weightAccToMoney', which balances sorting best chromosomes as it says.  Low values make it a upset betting machine, high values makes it mostly correct with conservative gains.
-Now total gains is a % against a hypothetical max, which replaced sorting heuristic mixing a % value and millions salts amount.
-Character match prediction is a more continuous math function, the old system just ADDED the weight as scoring point, now that weight scales by how the two characters compare. This change should help make betting more conservative between two equal skilled characters.  
-Also I reversed the score for ODDs, so the bigger odds character scoring is given to the lower, this helps with upset betting (i had like a +55% upsets correct at one point).
-Character win % is influenced by the win's sample size, without enough match data they move towards 50%, this helps against wins outliners, which is a problem with the bot.
-There are a few tweaks and optimizations, and has favor fixed stats from what a did weeks ago.
-Enjoy the enhanced Console prediction printout before each match. And check how  running: 'Simulator.prototype.evalMutations("mass"); (in the popup console) gives a few more details to top chromosome performance.   
-Aim for +60 acc && +7% gains (based on the sample matches file) && higher minimized losses than missed gains %'s.

### CODE REVIEW

**Comment by calexil** [comment]
looks good

**Comment by reconman** [comment]
@ACIIL Could you please squash the commits so they are combined into only a few? Please also fix the merge conflicts.

Makes merging easier for me. If I squashed instead of you, your next pull request would look even more horrible than this one because your original commits and my combinations of your commits will be in it.

You can find a guide on how to squash [here](http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html)

**Comment by reconman** [comment]
Video tutorial for squashing commits: https://youtu.be/9sQIY8c6J64?t=5m55s

**Comment by ACIIL** [comment]
I am lost and confused. First, this is from my developer branch which is working and already put on my master public branch, how do i properly pull request this over and without console use?  Answer why github and github desktop are not doing this automatically, because I ONLY SEE THE REBASE OPTION IF ITS A PERSONAL PULL REQUEST, why?    I have no idea how to manage this particular state on this page into a rebase.

**Comment by ACIIL** [comment]
I need instructions how to properly pull request my branch into the master. Look at what i have on my fork and say the order of commands to be done please.

**Comment by calexil** [comment]
close the pr, make a new pr with the testing branch selected

squash your commits

https://youtu.be/9sQIY8c6J64?t=5m55s

**Comment by reconman** [comment]
Sorry, I forgot about your comment. The Github desktop application only supports limited operations. The git command line tool can be used with other git based systems like Gitlab too. The Github desktop application just calls the git command line tool.

What you need to do to start is:

    git checkout develop
    git pull

Now comes the hard part. You have 166 commits in this pull request. You need to combine these 166 commits to only a few which are grouped by functionality.

First do
`git rebase -i HEAD~166`
to start the rebase process on all 166 commits.

You'll get a really long list of all the commits in this pull request in a vim based editor.

By pressing the key 'i' you can edit the text.

Replace the word 'pick' with 's' or 'squash' on the commits you want to combine with other commits. For example 

    pick <hash> Commit message 1
    s <hash> Commit message 2
    s <hash> Commit message 3

would get turned into one commit with all 3 commit messages. If you use 'fixup' or 'f' instead, commit message 2 and 3 will get discarded.

I would recommend reducing the 166 commits to 10 or fewer commits.

Once you have replaced the 'pick's on most commits with 'squash' or 'fixup', press Escape, then enter ':qw' and press Enter to escape the vim based commit editor. Git will then combine the commits.

After the rebasing you can do
`git log`
to see the cleaned up commit history.

If everything is as you want it, do `git push -f` to overwrite the 166 old commits with the new cleaned up ones.

If you mess up somewhere, do `git reset --hard origin/develop` to discard all changes.

It will take you some time to clean up your commits but as I've said in a comment above it's better if you do it instead of me because if I do it your next push request will be even harder to merge.

**Comment by calexil** [comment]
its a testing branch anyways... this is probably excessive.. but it was a mess

**Comment by ACIIL** [comment]
Doing this now.  From the vim stage, not only my commits are in there, but everyone before me. Which means anyone who forks will have the exact same problem as me with comments spam that is not my problem. I am going to squish their work in my fork.

**Comment by ACIIL** [comment]
The rebase is pulling in the "RankingTree" branch now. There are conflicts, need to understand it as i read the new code.

**Comment by ACIIL** [comment]
Having to fix merges of other peoples work is not fair, but i will try to anyways as i go.

**Comment by reconman** [comment]
@ACIIL What do you mean with fix merges of other people?

**Comment by ACIIL** [comment]
Going with git rebase -i HEAD~166  is  taking me from before i started. Going to reattempt this with exactly first commit now.

**Comment by reconman** [comment]
I think you can do it with `git rebase -i b970802` because that's the last commit I merged in your last pull request. The commits before that show up in this pull request because I squashed them after merging.

**Comment by ACIIL** [comment]
Well you are here. If i have the work flow of > new work branch > do some commits > Squash new branch as i pull it back in develop. Will you not see this commit spam problem anymore?  Because that was what i started doing in the last few weeks of work.   

Following that. You would want my early commits squished yes?

**Comment by reconman** [comment]
You can leave your early commits since I've squashed them already anyway.

new work branch > do some commits > Squash new branch is a good method for keeping the number of commits low.

Many of your commits have titles like "Code formatting", "Tweak" or "Merge ..." which should be squashed into other commits most of the time.

**Comment by ACIIL** [comment]
Are you saying my current development branch was edited and squished?  I am thinking i need to start my fork fresh anyways. 

 Trying to rebase is constantly bring back old conflict issues which i forgot. For example a time when  `Saltbot keep alive/:` folder and code was in there and then deleted.

**Comment by reconman** [comment]
Yeah, I combined all your commits from your last pull request into this commit https://github.com/synkarius/saltbot/commit/af831e6a332bab624881ce7cc2acf94cf7cad72c .

**Comment by reconman** [comment]
You could copy all your files to another folder, reset the branch to the remote state of my branch and then copy the files back. Then you can create new commits for the file changes.

I think that is the easiest way to start from scratch.

**Comment by ACIIL** [comment]
I see, it is a old commit though.  Still working on this rebase on my fork develop.

**Comment by ACIIL** [comment]
Have you liked my changes?

**Comment by reconman** [comment]
With the 166 commits listed here I haven't been able to determine what exactly you've changed in those last few commits. I would have to look through the commits one by one in their current state.

**Comment by ACIIL** [comment]
Regardless of how the commits are presented, you know you only need to look at the final diff. I would be surprised if you have not had test runs by now.

**Comment by reconman** [comment]
It shows me my changes too like the CSS changes for the buttons.

**Comment by ACIIL** [comment]
Now i am confused.   My work flow:

Started fork from synkarius/saltbot into ACIIL/saltbot.
Created ACIIL/develop branch from ACIIL/saltbot, now treat ACIIL/saltbot branch as "working public" branch.
From ACIIL/develop, do daily branches and/or /tons/ of commits in them, pull request these branches into ACIIL/develop.
Get out of sync, periodically pull from  synkarius/saltbot into ACIIL/develop when it updates or release ready.
Pull request into synkarius/new-mutation-method When i have something ready to present.

This make sense?

**Comment by reconman** [comment]
Yep, makes sense.

**Comment by ACIIL** [comment]
So everytime i get in sync, you will see your changes.  Must i attempt pull requests and not do merge conflicts (if they are there) in the sync before i do? Mind you if i knew my fork is accepted in synkarius/saltbot master  I would not need to keep sync'ing in such a off branch.

**Comment by reconman** [comment]
To avoid seeing my own commits in your pull requests you would need to refrain from pulling new commits from the master branch.

I could merge my commits listed in this pull request into the branch to correct the file change summary tab.

**Comment by reconman** [comment]
Sadly merging the commits did nothing if I only merge single commits with `git cherry-pick`.

**Comment by ACIIL** [comment]
Yes, please sync this mutation branch with master.  Actually I find myself changing more then the mutation and evolution sim content these days, I think to stay relevant i need to pull request in the synkarius/saltbot  master from this point on.

Lately i had changed things like tournament confidence betting,  character statistical data records,  better character prediction. performance increases, etc. Next i am looking at the character stats objects.  Such changes do not fit the nature of this branch.

Are you prepared to accept my code?  In the future I will squish commits in the daily work branches like now and keep commits tight, and keep you happy. 

There won't be any new code updates from me anytime soon, because i gotten burned from the code these past few months. I think this pull request request was a "swan song" before i go for awhile.

**Comment by ACIIL** [comment]
I'm still challenging myself to rebase all this and working on it atm. lol

**Comment by reconman** [comment]
I've pulled the commits from master to new-mutation-method but somehow they are still displayed in the list of commits in this pull request. Maybe they are gone if you create a new pull request?

**Comment by reconman** [comment]
I will accept your code once the commit history is cleaned up.

**Comment by ACIIL** [comment]
Give me time to fix the rebase of my develop branch.    If i will reattempt a pull request i want my develop commit history nice first for you.  Even then it will be behind recent updates as i have not touched the code in weeks nor want to see the changes.

Also github desktop will be in a "pull look" on my develop branch until i close this or get accepted. So A new request is assured now. :(

You want me to pull into the same test branch i take it?

**Comment by ACIIL** [comment]
Rebase complete. Doing some fixing, and will test if it runs.  After that i will let you see if the commits are as clean as you want them in a pull request test.

**Comment by reconman** [comment]
You still need to get rid of your old commits. After rebasing you have to do a `git push -f` in order to overwrite the old commits with the squashed ones.

At this point what you need to do to reach the same result is rebase all the commits in this pull request and replace the pick with drop for all the ones before your 4 new ones and then after rebasing do `git push -f`.

**Comment by ACIIL** [comment]
How is my develop branch git history now?  I rebased from b970802, and left <10 skips from some important commit points, the rest were 's'. Then made a commit fixing a rebase error (ad3164547ada2326c06137d5c6ccec66e369433a), then `git push -f`, and finally made develop my main branch. Still, when i look at the git log many commits are independent, but i do see chains commit lines together.

I had to redo the entire conflict history from the past to get to this point, i read now  rebasing will not fix conflicts like i already did.  I will not be able to rebase like this again if it means redoing the exact same conflict resolution again for every rebase.    At this point i will not rebase commits before new ones today, no one should be forced to redo merge conflicts to to make commits more "readable" by someones preference.

**Comment by ACIIL** [comment]
actually im going to do the old-age refork again  and paste my code over the first commit. I am not happy losing records of my contribution this way.

**Comment by reconman** [comment]
Sorry to cause so much work for you but I didn't want to fill the commit history with hundreds of tiny commits. I could have squashed them myself after merging but then your next pull request would have even more commits in it.

I hope you can manage to somehow commit your changes.

**Pull request closed without merging**
