### PR TITLE
Readme edits, data restructuring, bug reports etc.

### PR DESCRIPTION
**Pull request by calexil**

### CODE REVIEW

**Comment by calexil** [comment]
@reconman I just did some cleanup to beautify the git, and fixed a few small errors here. As well as pointed to the bug reporting guide in the readme (not sure why this hadn't been done yet :+1: )

**Comment by calexil** [comment]
@reconman none of my changes here mess with the core functionality, this was a cleanup pr

**Comment by calexil** [comment]
[clabot:check]

**Comment by calexil** [comment]
clabot:check

**Comment by calexil** [comment]
@reconman  poke

**Comment by calexil** [comment]
u ded?

**Comment by reconman** [comment]
No, just pretty busy with a fulltime job and writing my Master's thesis.

**Comment by calexil** [comment]
ah

**Pull request merged**
