### PR TITLE
image fixes

### PR DESCRIPTION
**Pull request by calexil**
readme edits

### CODE REVIEW

**Comment by reconman** [comment]
Why are you creating pull requests when you have rights to push to this repository?

You know, you could just create branches on synkarius/saltbot, do your commits there, rebase and merge it into master.

**Comment by reconman** [comment]
Pull requests have no benefit if you merge them yourself. In big companies the developers create pull requests and someone else reviews all changes and merges them.

**Comment by ACIIL** [comment]
This  will lead to my same problem of needing to keep commits controlled by squishing in branches. 

Do the style of->branch from, keep a chain of edit commits until you are super ready locally, pull request and squish if you have permission.

There are ways to do append commits and such, good for backtracking fixes in you local branch being edited.

**Comment by calexil** [comment]
It makes it so my fork and master are a mirror.

but if you dont like it.. Ill just push to master

**Pull request merged**
