### PR TITLE
Added functionality for exporting and importing chromosomes

### LINKED ISSUE #23: Import-export chromosomes

### PR DESCRIPTION
**Pull request by reconman**
Fixes #23 

The popup.html had to be changed a bit because the maximum height of
popups is 600 px. If the Developer header is left it needs more than 600
px height.

toJSON() is called when JSON.stringify() is called which leads to an
endless loop. Either rename the function or just leave it removed as
it's not used anywhere.

### CODE REVIEW

**Comment by synkarius** [comment]
That is some fine work. I think I'm going to start saving a chromosome every month.

**Comment by reconman** [comment]
The hardest part was finding out why chromosomes_v1[0].toJSON didn't work. You can see during execution that it contains all the properties of a chromosome but won't be treated as one. You specifically need to create a new Chromosome and read the data from the Object.

Casting would be so much easier...

**Comment by reconman** [comment]
The hardest part was finding out why chromosomes_v1[0].toJSON() didn't work. It's because it's an Object, not a Chromosome. You can see during execution that it contains all the properties of a chromosome but won't be treated as one. You specifically need to create a new Chromosome and read the data from the Object.

Casting would be so much easier...

**Comment by synkarius** [comment]
I agree, casting would be nice. Do you also program in some other language? My main is actually Java.

**Comment by reconman** [comment]
My main is Java too. Additionally, I've learned C++ for 1 1/2 years and C# for half a year. HTML, PHP and Javascript weren't really the focus in my degree course.

**Comment by synkarius** [comment]
I think I'd like to learn C++ at some point.

**Comment by reconman** [comment]
It's a hell of pointers and non-existing methods.

Want to concatenate some strings, ints, doubles?
Looks like this:
> string s = "text";
int i = 5;
double d = 0.2;
std::stringstream ss;
ss << "string: " << s << "int: " << i << ", double: " << d;
//print to console
std::cout << ss.str(); << std::endl;

Or how about creating an object in a function and returning the object reference?
> A & createA() {
   A a;
   return a;
}

Nope, doesn't work without calling the copy-constructor. The only choice would be to do it like this:
> A* createA() {
  A* a = new A();
  return a;
}

And everytime you use the object you have to write *a because it's a pointer to an object. And in the end you have to write delete a; if you don't want to use it anymore because else the memory is still allocated.
 
There's no refactoring support and imports must be done by hand.

Sorry for the little rant, but I'd prefer C# over C++ a thousand times.

**Comment by synkarius** [comment]
Hah! No worries, I can enjoy a good rant. I guess I meant that more in the sense that learning C++ would force me to understand what's going on under the hood with the other languages I use, not so much in the sense that I actually want to use it.

**Comment by reconman** [comment]
If it's about that I can recommend a book about OOP. It explains the mechanisms behind everything.

What's your email address so I can contact you?

**Comment by synkarius** [comment]
I'm always up for a good book suggestion. I don't like posting my email in public, but if you contact me [at this contact form](http://explosionduck.com/wp/contact/), I'll email you.

**Pull request merged**
